name: Deploy ai-data-platform
run-name: "[${{ inputs.environment }}] Deploy Environment Core"

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment"
                default: "dev"
                required: true
                type: choice
                options:
                    - dev
                    - test
                    - prod

permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        uses: Omid-Pa/omid-ai-infra/.github/workflows/deploy-terraform.yml@main
        with:
            environment: ${{ inputs.environment }}
            terraform-directory-name: ai-data-platform
